services:
  redis:
    image: redis:alpine
    container_name: meme-redis
    restart: always
    ports:
      - "6379:6379"

  memegen:
    container_name: memegen
    image: astrognome/memegen
    ports:
      - "5000:5000"
    restart: always

  postgres:
    image: postgres:14-alpine
    container_name: meme-postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
