services:
  redis:
    image: redis:alpine
    container_name: meme-redis
    restart: always
    ports:
      - "6379:6379"

  memegen:
    container_name: memegen
    image: astrognome/memegen
    ports:
      - "5002:5000"
    restart: always
